version: "3"
services:
  app:
    build: ./app
    user: root
    volumes:
      - ./app:/app
    tty: true
    ports:
      - "8889:8889"
    command:
      jupyter lab
        --port=8889
        --ip=0.0.0.0
        --allow-root
        --NotebookApp.token=''
        --no-browser
