version: "3"
services:
  postgres:
    build: ./db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - ./db/data/postgres:/var/lib/postgresql/data
  app:
    build: ./app
    user: root
    volumes:
      - ./app:/app
    tty: true
    ports:
      - "8889:8889"
    command:
      jupyter lab
        --port=8889
        --ip=0.0.0.0
        --allow-root
        --NotebookApp.token=''
        --no-browser
