version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:202007-01

    steps:
      - checkout

      - run:
          name: Confirm directory state
          command: |
            set -x
            pwd && ls

      - run:
          name: Build Docker container
          command: |
            set -x
            docker-compose build

      - run:
          name: Up Docker containers and Confirm logs
          command: |
            set -x
            docker-compose up -d
            sleep 5
            docker ps -f status=running
            docker-compose logs
            docker-compose run --rm app bash -c "python --version && poetry --version"
            docker-compose run --rm db bash -c "psql --version"

      - run:
          name: Run Pytest
          command: |
            set -x
            docker-compose run --rm app sh -c "pytest"

      - run:
          name: Down Docker container and Finish pipeline
          command: |
            set -x
            docker-compose down
            echo "finish pipeline"
